<?php

namespace Database\Factories;

use App\Models\Client;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class OpportunityFactory extends Factory
{
    public function definition(): array
    {
        return [
            // opp_number is auto-generated by the model boot hook
            'client_id'           => Client::factory(),
            'sales_id'            => User::factory()->sales(),
            'product_id'          => null,
            'title'               => fake()->sentence(4),
            'stage'               => 'prospecting',
            'estimated_value'     => fake()->randomFloat(2, 1_000_000, 100_000_000),
            'final_value'         => null,
            'pax'                 => null,
            'discount_percent'    => 0,
            'discount_approved'   => false,
            'approved_by'         => null,
            'expected_close_date' => now()->addMonths(2)->toDateString(),
            'actual_close_date'   => null,
            'lost_reason'         => null,
            'notes'               => null,
            'booking_id'          => null,
            'subscription_id'     => null,
        ];
    }

    public function prospecting(): static
    {
        return $this->state(['stage' => 'prospecting']);
    }

    public function proposal(): static
    {
        return $this->state(['stage' => 'proposal']);
    }

    public function negotiation(): static
    {
        return $this->state(['stage' => 'negotiation']);
    }

    public function won(): static
    {
        return $this->state([
            'stage'              => 'won',
            'actual_close_date'  => now()->toDateString(),
        ]);
    }

    public function lost(): static
    {
        return $this->state([
            'stage'       => 'lost',
            'lost_reason' => fake()->sentence(),
        ]);
    }
}
