<?php

namespace Database\Factories;

use App\Models\Client;
use Illuminate\Database\Eloquent\Factories\Factory;

class SubscriptionFactory extends Factory
{
    public function definition(): array
    {
        return [
            // sub_number is auto-generated by the model boot hook
            'opportunity_id'    => null,
            'client_id'         => Client::factory(),
            'vehicle_id'        => null,
            'driver_id'         => null,
            'product_id'        => null,
            'start_date'        => today()->toDateString(),
            'end_date'          => today()->addYear()->toDateString(),
            'monthly_rate'      => fake()->randomFloat(2, 1_000_000, 20_000_000),
            'billing_cycle'     => 'monthly',
            'status'            => 'active',
            'last_billed_at'    => null,
            'next_billing_date' => today()->toDateString(),
            'auto_renew'        => true,
            'notes'             => null,
        ];
    }

    public function active(): static
    {
        return $this->state(['status' => 'active']);
    }

    public function terminated(): static
    {
        return $this->state([
            'status'   => 'terminated',
            'end_date' => today()->toDateString(),
        ]);
    }
}
